services:
  mariadb:
    image: 'mariadb:latest'
    restart: 'always'
    environment:
      MARIADB_DATABASE: 'web-chat'
      MARIADB_PASSWORD: 'secret'
      MARIADB_ROOT_PASSWORD: 'verysecret'
      MARIADB_USER: 'arkham'
    ports:
      - '3306'
    volumes:
      - 'data:/var/lib/mysql'
  tomcat:
    image: 'tomcat:jre17-temurin-jammy'
    ports:
      - '8888:8080'
      - '5005:5005'
    command: 'catalina.sh run'
    volumes:
      - './build/libs:/usr/local/tomcat/webapps'
    environment:
      JAVA_OPTS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
volumes:
  data:
